import type { CardDef } from './types';

export const CARD_DEFS: Record<string, CardDef> = {
  spark_core: {
    id: 'spark_core',
    name: 'Spark Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'FIRE',
    hp: 3,
    attack: 0,
    rulesText: 'Physical generator. Produces 1 energy/turn. Can be burned and destroyed.',
    effectKey: 'none',
  },
  spring_core: {
    id: 'spring_core',
    name: 'Spring Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'WATER',
    hp: 3,
    attack: 0,
    rulesText: 'Physical generator. Produces 1 energy/turn. Water-based — resists fire.',
    effectKey: 'none',
  },
  emberling: {
    id: 'emberling',
    name: 'Emberling',
    type: 'CREATURE',
    cost: 1,
    element: 'FIRE',
    hp: 3,
    attack: 1,
    collisionEnergy: 3,
    rulesText: 'Advances toward enemy base. On a structure, explodes to burn sand nearby. Dissipates after 3 collisions.',
    effectKey: 'fire_spray',
  },
  water_wisp: {
    id: 'water_wisp',
    name: 'Water Wisp',
    type: 'CREATURE',
    cost: 1,
    element: 'WATER',
    hp: 3,
    attack: 1,
    collisionEnergy: 4,
    rulesText: 'Glides toward enemy base. On a structure, emits a cutting water beam. Dissipates after 4 collisions.',
    effectKey: 'water_beam',
  },
  stone_mite: {
    id: 'stone_mite',
    name: 'Stone Mite',
    type: 'CREATURE',
    cost: 2,
    element: 'EARTH',
    hp: 5,
    attack: 1,
    collisionEnergy: 5,
    rulesText: 'Slow crawler toward enemy base. On a structure, delivers a crushing sand impact. Dissipates after 5 collisions.',
    effectKey: 'sand_burst',
  },
  splash: {
    id: 'splash',
    name: 'Splash',
    type: 'SPELL',
    cost: 1,
    element: 'WATER',
    rulesText: 'Fires a water beam from your base toward target. Water extinguishes fire.',
    effectKey: 'water_beam',
    spellDamage: 1,
  },
  ignite: {
    id: 'ignite',
    name: 'Ignite',
    type: 'SPELL',
    cost: 1,
    element: 'FIRE',
    rulesText: 'Fires a fire spray from your base toward target. Fire erodes core cells.',
    effectKey: 'fire_spray',
    spellDamage: 1,
  },
  collapse: {
    id: 'collapse',
    name: 'Collapse',
    type: 'SPELL',
    cost: 2,
    element: 'EARTH',
    rulesText: 'Drops heavy sand from above onto target. High volume — buries units.',
    effectKey: 'sand_burst',
    spellDamage: 2,
  },

  // ── Structure cards ───────────────────────────────────────────────────────
  stone_wall: {
    id: 'stone_wall',
    name: 'Stone Wall',
    type: 'STRUCTURE',
    cost: 1,
    element: 'EARTH',
    rulesText: 'Places a solid 12-wide stone barrier. Blocks sand, water, and fire. Erodes under sustained fire.',
    effectKey: 'none',
    structureShape: 'wall_line',
  },
  channel: {
    id: 'channel',
    name: 'Channel',
    type: 'STRUCTURE',
    cost: 2,
    element: 'EARTH',
    rulesText: 'Places two stone rails with a gap. Channels water and sand through the corridor.',
    effectKey: 'none',
    structureShape: 'channel',
  },
  firebreak: {
    id: 'firebreak',
    name: 'Firebreak',
    type: 'STRUCTURE',
    cost: 1,
    element: 'EARTH',
    rulesText: 'Places a sparse alternating stone barrier. Slows fire spread — does not fully stop it.',
    effectKey: 'none',
    structureShape: 'firebreak',
  },
};

export const PLAYER_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash', 'splash',
  'ignite',
  'collapse',
  'stone_wall', 'stone_wall',
  'channel',
  'firebreak',
];

export const ENEMY_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash',
  'ignite', 'ignite',
  'collapse',
];
