import type { CardDef } from './types';

export const CARD_DEFS: Record<string, CardDef> = {
  spark_core: {
    id: 'spark_core',
    name: 'Spark Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'FIRE',
    hp: 3,
    attack: 0,
    rulesText: 'Produces 1 energy per turn.',
    effectKey: 'none',
  },
  spring_core: {
    id: 'spring_core',
    name: 'Spring Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'WATER',
    hp: 3,
    attack: 0,
    rulesText: 'Produces 1 energy per turn.',
    effectKey: 'none',
  },
  emberling: {
    id: 'emberling',
    name: 'Emberling',
    type: 'CREATURE',
    cost: 1,
    element: 'FIRE',
    hp: 3,
    attack: 1,
    rulesText: 'Attack: sprays fire sparks at target.',
    effectKey: 'fire_spray',
  },
  water_wisp: {
    id: 'water_wisp',
    name: 'Water Wisp',
    type: 'CREATURE',
    cost: 1,
    element: 'WATER',
    hp: 3,
    attack: 1,
    rulesText: 'Attack: shoots water beam. Water extinguishes fire.',
    effectKey: 'water_beam',
  },
  stone_mite: {
    id: 'stone_mite',
    name: 'Stone Mite',
    type: 'CREATURE',
    cost: 2,
    element: 'EARTH',
    hp: 5,
    attack: 1,
    rulesText: 'Attack: launches a clump of falling sand.',
    effectKey: 'sand_burst',
  },
  splash: {
    id: 'splash',
    name: 'Splash',
    type: 'SPELL',
    cost: 1,
    element: 'WATER',
    rulesText: 'Deal 1 damage to a target. Creates water pixels.',
    effectKey: 'water_beam',
    spellDamage: 1,
  },
  ignite: {
    id: 'ignite',
    name: 'Ignite',
    type: 'SPELL',
    cost: 1,
    element: 'FIRE',
    rulesText: 'Deal 1 damage to a target. Creates fire pixels.',
    effectKey: 'fire_spray',
    spellDamage: 1,
  },
  collapse: {
    id: 'collapse',
    name: 'Collapse',
    type: 'SPELL',
    cost: 2,
    element: 'EARTH',
    rulesText: 'Deal 2 damage to a target. Drops sand from above.',
    effectKey: 'sand_burst',
    spellDamage: 2,
  },
};

export const PLAYER_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash', 'splash',
  'ignite',
  'collapse',
];

export const ENEMY_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash',
  'ignite', 'ignite',
  'collapse',
];
