import type { CardDef } from './types';

export const CARD_DEFS: Record<string, CardDef> = {
  spark_core: {
    id: 'spark_core',
    name: 'Spark Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'FIRE',
    hp: 3,
    attack: 0,
    rulesText: 'Produces 1 energy per turn.',
    effectKey: 'none',
  },
  spring_core: {
    id: 'spring_core',
    name: 'Spring Core',
    type: 'GENERATOR',
    cost: 0,
    element: 'WATER',
    hp: 3,
    attack: 0,
    rulesText: 'Produces 1 energy per turn.',
    effectKey: 'none',
  },
  emberling: {
    id: 'emberling',
    name: 'Emberling',
    type: 'CREATURE',
    cost: 1,
    element: 'FIRE',
    hp: 3,
    attack: 1,
    rulesText: 'Attack: sprays fire sparks at target.',
    effectKey: 'fire_spray',
  },
  water_wisp: {
    id: 'water_wisp',
    name: 'Water Wisp',
    type: 'CREATURE',
    cost: 1,
    element: 'WATER',
    hp: 3,
    attack: 1,
    rulesText: 'Attack: shoots water beam. Water extinguishes fire.',
    effectKey: 'water_beam',
  },
  stone_mite: {
    id: 'stone_mite',
    name: 'Stone Mite',
    type: 'CREATURE',
    cost: 2,
    element: 'EARTH',
    hp: 5,
    attack: 1,
    rulesText: 'Attack: launches a clump of falling sand.',
    effectKey: 'sand_burst',
  },
  splash: {
    id: 'splash',
    name: 'Splash',
    type: 'SPELL',
    cost: 1,
    element: 'WATER',
    rulesText: 'Deal 1 damage to a target. Creates water pixels.',
    effectKey: 'water_beam',
    spellDamage: 1,
  },
  ignite: {
    id: 'ignite',
    name: 'Ignite',
    type: 'SPELL',
    cost: 1,
    element: 'FIRE',
    rulesText: 'Deal 1 damage to a target. Creates fire pixels.',
    effectKey: 'fire_spray',
    spellDamage: 1,
  },
  collapse: {
    id: 'collapse',
    name: 'Collapse',
    type: 'SPELL',
    cost: 2,
    element: 'EARTH',
    rulesText: 'Deal 2 damage to a target. Drops sand from above.',
    effectKey: 'sand_burst',
    spellDamage: 2,
  },

  // ── Structure cards ───────────────────────────────────────────────────────
  stone_wall: {
    id: 'stone_wall',
    name: 'Stone Wall',
    type: 'STRUCTURE',
    cost: 1,
    element: 'EARTH',
    rulesText: 'Place a solid stone wall that blocks sand, water, and fire. Erodes under sustained fire.',
    effectKey: 'none',
    structureShape: 'wall_line',
  },
  channel: {
    id: 'channel',
    name: 'Channel',
    type: 'STRUCTURE',
    cost: 2,
    element: 'EARTH',
    rulesText: 'Place two stone rails that guide water and sand through a narrow corridor.',
    effectKey: 'none',
    structureShape: 'channel',
  },
  firebreak: {
    id: 'firebreak',
    name: 'Firebreak',
    type: 'STRUCTURE',
    cost: 1,
    element: 'EARTH',
    rulesText: 'Place a sparse stone barrier with gaps that slows fire spread but does not fully block it.',
    effectKey: 'none',
    structureShape: 'firebreak',
  },
};

export const PLAYER_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash', 'splash',
  'ignite',
  'collapse',
  'stone_wall', 'stone_wall',
  'channel',
  'firebreak',
];

export const ENEMY_STARTING_DECK: string[] = [
  'spark_core', 'spark_core',
  'spring_core', 'spring_core',
  'emberling', 'emberling',
  'water_wisp', 'water_wisp',
  'stone_mite',
  'splash',
  'ignite', 'ignite',
  'collapse',
];
